spring.application.name=backendApp
spring.mongodb.uri=mongodb://localhost:27017/ai_support_db
spring.data.mongodb.database=ai_support_db
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.1
# ===============================
# Kafka Configuration
# ===============================

spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# Consumer
spring.kafka.consumer.group-id=ticket-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.backendwork.backendApp.events
spring.kafka.consumer.properties.spring.json.value.default.type=com.backendwork.backendApp.events.TicketEvent